### ISSUE TITLE
How to auto add these whitelists to the pi-hole filter?

### ISSUE THREAD

**Issue by DarthKeizer** [deathbybandaid/pihole-whitelists#1]
Might be I have missed it somewhere, but it is not quite clear?
Thanks in advance and keep up the good work 👍 !

**Comment by deathbybandaid** [comment]
Currently there isn't a way,,, See this thread:

https://www.reddit.com/r/pihole/comments/66dwwx/wally3k_whitelist_domain_suggestion_and_help/dghvjz3/


Especially, what PromoFaux says. Essentially, the idea would be to have a gravity for good things

**Comment by DarthKeizer** [comment]
Ah okay thanks man! This issue is then resolved 👍
